set(PN_LIB_CORE_MAJOR_VERSION 10)
set(PN_LIB_CORE_MINOR_VERSION 11)
set(PN_LIB_CORE_PATCH_VERSION 0)
set(PN_LIB_CORE_VERSION "${PN_LIB_CORE_MAJOR_VERSION}.${PN_LIB_CORE_MINOR_VERSION}.${PN_LIB_CORE_PATCH_VERSION}")

set(PN_LIB_PROACTOR_MAJOR_VERSION 1)
set(PN_LIB_PROACTOR_MINOR_VERSION 7)
set(PN_LIB_PROACTOR_PATCH_VERSION 1)
set(PN_LIB_PROACTOR_VERSION "${PN_LIB_PROACTOR_MAJOR_VERSION}.${PN_LIB_PROACTOR_MINOR_VERSION}.${PN_LIB_PROACTOR_PATCH_VERSION}")

set(PN_LIB_LEGACY_MAJOR_VERSION 11)
set(PN_LIB_LEGACY_MINOR_VERSION 12)
set(PN_LIB_LEGACY_PATCH_VERSION 0)
set(PN_LIB_LEGACY_VERSION "${PN_LIB_LEGACY_MAJOR_VERSION}.${PN_LIB_LEGACY_MINOR_VERSION}.${PN_LIB_LEGACY_PATCH_VERSION}")
