set(PN_LIB_CPP_MAJOR_VERSION 12)
set(PN_LIB_CPP_MINOR_VERSION 3)
set(PN_LIB_CPP_PATCH_VERSION 0)
set(PN_LIB_CPP_VERSION "${PN_LIB_CPP_MAJOR_VERSION}.${PN_LIB_CPP_MINOR_VERSION}.${PN_LIB_CPP_PATCH_VERSION}")
