#! /bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Usage: send [-a ADDRESS] [-s SUBJECT] MESSAGE ... MESSAGE
# sends each arg as a text-message to the given adress (by default, to amqp://localhost/test)

HERE=$(cd $(dirname $0); pwd)
TOP=$(cd $(dirname $0); cd  ../../..; pwd)
LIBS=$HERE/target/classes:$TOP/proton-j/target/classes
JFLAGS="-Djava.util.logging.config.file=$HERE/send.trace.props -cp $LIBS"
java -cp $LIBS org.apache.qpid.proton.example.Send "$@"

